In [1]:
import numpy as np
from CFR_player import Subgame, CFRPlayer
from utils import GameState

In [2]:
board = -np.ones((3,3))
board[0,2] = 0
board[1,1] = 1
board[2,1] = 0
print(board)
num_players = 2
game_state = GameState(board, num_players, 1)
my_number = 1

[[-1. -1.  0.]
 [-1.  1. -1.]
 [-1.  0. -1.]]


In [3]:
CFRPlayer().get_move(game_state)

length of children: 0


In [4]:
subgame = Subgame(board, num_players, my_number, 1, 0)
subgame.display_children()

In [7]:
subgame.is_terminal_node()

True

In [11]:
subgame.children[0].children[0].children[0].display_children()

Board (1.000) - Player 0
[[ 1.  0.  1.]
 [ 0.  1.  0.]
 [-1. -1.  0.]]
Board (0.000) - Player 0
[[ 1.  0.  1.]
 [ 0.  1. -1.]
 [ 0. -1.  0.]]
Board (1.000) - Player 0
[[ 1.  0.  1.]
 [ 0.  1. -1.]
 [-1.  0.  0.]]


In [8]:
subgame.children[0].display_board()

Board (0.000) - Player 0
[[ 1. -1. -1.]
 [ 1.  0. -1.]
 [-1. -1. -1.]]


In [6]:
subgame.children[1].children[3].display_children()

Board (1.000) - Player 0
[[ 1.  0.  0.]
 [ 0.  0.  1.]
 [-1. -1.  1.]]
Board (1.000) - Player 0
[[ 1. -1.  0.]
 [ 0.  0.  1.]
 [ 0. -1.  1.]]
Board (1.000) - Player 0
[[ 1. -1.  0.]
 [ 0.  0.  1.]
 [-1.  0.  1.]]


In [9]:
subgame.children[1].children[3].children[2].display_children()

Board (1.000) - Player 1
[[ 1.  1.  0.]
 [ 0.  0.  1.]
 [-1.  0.  1.]]
Board (1.000) - Player 1
[[ 1. -1.  0.]
 [ 0.  0.  1.]
 [ 1.  0.  1.]]


In [12]:
child = subgame.children[1]
player_board = child.board == child.node_player

In [18]:
player_board

AttributeError: 'numpy.ndarray' object has no attribute 'fliplr'